import type { INodeProperties } from 'n8n-workflow';

const show = {
	operation: ['create'],
	resource: ['contact'],
};

export const contactCreateDescription: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show },
		description: 'The name of the contact',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show },
		default: {},
		options: [
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				routing: { send: { type: 'body', property: 'email' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'phone' } },
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'mobile' } },
			},
			{
				displayName: 'Document (CPF/CNPJ)',
				name: 'document',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'document' } },
			},
			{
				displayName: 'Person Type',
				name: 'person_type',
				type: 'options',
				options: [
					{ name: 'Individual', value: 'individual' },
					{ name: 'Company', value: 'company' },
				],
				default: 'individual',
				routing: { send: { type: 'body', property: 'person_type' } },
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Lead', value: 'lead' },
					{ name: 'Customer', value: 'customer' },
					{ name: 'Prospect', value: 'prospect' },
					{ name: 'Supplier', value: 'supplier' },
				],
				default: 'lead',
				routing: { send: { type: 'body', property: 'type' } },
			},
			{
				displayName: 'Source',
				name: 'source',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'source' } },
			},
			{
				displayName: 'Company Name',
				name: 'company',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'company' } },
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'position' } },
			},
			{
				displayName: 'Website',
				name: 'website',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'website' } },
			},
			{
				displayName: 'Trading Name',
				name: 'trading_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'trading_name' } },
			},
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'address' } },
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'city' } },
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'state' } },
			},
			{
				displayName: 'ZIP Code',
				name: 'zip_code',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'zip_code' } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'country' } },
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'dateTime',
				default: '',
				routing: { send: { type: 'body', property: 'birth_date' } },
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { send: { type: 'body', property: 'notes' } },
			},
			{
				displayName: 'Group ID',
				name: 'contact_group_id',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'contact_group_id' } },
			},
			{
				displayName: 'Assigned To (User ID)',
				name: 'assigned_to',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'assigned_to' } },
			},
			{
				displayName: 'Parent ID',
				name: 'parent_id',
				type: 'number',
				default: 0,
				description: 'Parent company contact ID (for employees)',
				routing: { send: { type: 'body', property: 'parent_id' } },
			},
		],
	},
];
