import type { INodeProperties } from 'n8n-workflow';

const show = {
	operation: ['create'],
	resource: ['product'],
};

export const productCreateDescription: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show },
		description: 'The name of the product',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show },
		description: 'The price of the product',
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		displayOptions: { show },
		default: {},
		options: [
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'sku' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
				routing: { send: { type: 'body', property: 'description' } },
			},
			{
				displayName: 'Short Description',
				name: 'short_description',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'short_description' } },
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Product', value: 'product' },
					{ name: 'Service', value: 'service' },
				],
				default: 'product',
				routing: { send: { type: 'body', property: 'type' } },
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'category' } },
			},
			{
				displayName: 'Category ID',
				name: 'category_id',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'category_id' } },
			},
			{
				displayName: 'Cost',
				name: 'cost',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'cost' } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'BRL',
				routing: { send: { type: 'body', property: 'currency' } },
			},
			{
				displayName: 'Unit',
				name: 'unit',
				type: 'string',
				default: '',
				description: 'Unit of measurement (e.g. un, kg, hr)',
				routing: { send: { type: 'body', property: 'unit' } },
			},
			{
				displayName: 'Tax Rate (%)',
				name: 'tax_rate',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'tax_rate' } },
			},
			{
				displayName: 'Track Stock',
				name: 'track_stock',
				type: 'boolean',
				default: false,
				routing: { send: { type: 'body', property: 'track_stock' } },
			},
			{
				displayName: 'Stock Quantity',
				name: 'stock_quantity',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'stock_quantity' } },
			},
			{
				displayName: 'Min Stock',
				name: 'min_stock',
				type: 'number',
				default: 0,
				routing: { send: { type: 'body', property: 'min_stock' } },
			},
			{
				displayName: 'Is Active',
				name: 'is_active',
				type: 'boolean',
				default: true,
				routing: { send: { type: 'body', property: 'is_active' } },
			},
		],
	},
];
